app/urls.py
from django.urls import path

from . import views

app_name = 'app'

urlpatterns = [
    path('', views.mainpage),
    path('sightings/', views.list),
    path('sightings/stats/', views.stats, name = 'stats'),
    path('sightings/add/', views.add, name = 'add'),
    path('map/', views.map, name = 'map'),
    path('sightings/<str:unique_squirrel_id>/', views.edit, name='edit'),
]

project/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('app.urls')),
]

app/models.py
from django.db import models

from django.utils.translation import gettext as _




class Squirrel(models.Model):


    unique_squirrel_id = models.CharField(
        max_length=100,
        help_text=_('Unique id of squirrel'),
        primary_key=True,
        default=None,
    )

    X = models.FloatField(
        max_length=100,
        help_text=_('Longitude'),
        default=None,
    )

    Y = models.FloatField(
        max_length=100,
        help_text=_('Latitude'),
        default=None,
    )
    
    PM = 'PM'
    AM = 'AM'

    SHIFT_CHOICES = [
        (PM, _('PM')),
        (AM, _('AM')),
    ]

    shift = models.CharField(
        max_length=2,
        help_text=_('Occur before or after noon'),
        choices=SHIFT_CHOICES,
        default=AM,
    )

    date = models.DateField(
        help_text=_('Occur Date'),
        default=None,
        blank=True,
        null=True,
    )
    
    ADULT = 'Adult'
    JUVENILE = 'Juvenile'

    AGE_CHOICES = [
        (ADULT, _('Adult')),
        (JUVENILE, _('Juvenile')),
    ]

    age = models.CharField(
        max_length=10,
        help_text=_('Age of squirrel_Adult or Juvenile'),
        choices=AGE_CHOICES,
        blank=True,
        null=True,
    )
    
    GRAY = 'Gray'
    CINNAMON = 'Cinnamon'
    BLACK = 'Black'
    
    PRIMARY_FUR_COLOR_CHOICES = [
        (GRAY, _('Gray')),
        (CINNAMON, _('Cinnamon')),
        (BLACK, _('Black')),
    ]
    
    primary_fur_color = models.CharField(
        max_length=15,
        help_text=_('Choose the primary fur color for the squirrel'),
        choices=PRIMARY_FUR_COLOR_CHOICES,
        blank=True,
        null=True,
    )
    
    GROUND_PLANE = 'Ground Plane'
    ABOVE_GROUND = 'Above Ground'
    
    LOCATION_CHOICES = [
        (GROUND_PLANE, _('Ground Plane')),
        (ABOVE_GROUND, _('Above Ground')),
    ]
    
    location = models.CharField(
        max_length=30,
        help_text=_('Location of squirrel, choose from options'),
        choices=LOCATION_CHOICES,
        blank=True,
        null=True,
    )
    
    specific_location = models.TextField(
        default=None,
        null=True,
        blank=True,
        help_text=_('Additional location information'),
    )
    
    running = models.BooleanField(
        help_text=_('Is squirrel seen running'),
        default=False,
    )
    
    chasing = models.BooleanField(
        help_text=_('Is squirrel seen chasing'),
        default=False,
    )
    
    climbing = models.BooleanField(
        help_text=_('Is squirrel seen climbing'),
        default=False,
    )
    
    eating = models.BooleanField(
        help_text=_('Is squirrel seen eating'),
        default=False,
    )
    
    foraging = models.BooleanField(
        help_text=_('Is squirrel seen foraging'),
        default=False,
    )
    
    other_activities = models.TextField(
        blank=True,
        default=None,
        null=True,
        help_text=_('Additional activities information'),
    )
    
    kuks = models.BooleanField(
        help_text=_('Is squirrel seen kuks'),
        default=False,
    )
    
    quaas = models.BooleanField(
        help_text=_('Is squirrel seen quaas'),
        default=False,
    )
    
    moans = models.BooleanField(
        help_text=_('Is squirrel seen moans'),
        default=False,
    )
    
    tail_flags = models.BooleanField(
        help_text=_('Is squirrel flaging tail'),
        default=False,
    )
    
    tail_twitches = models.BooleanField(
        help_text=_('Is squirrel twitching tail'),
        default=False,
    )
    
    approaches = models.BooleanField(
        help_text=_('Is squirrel approaching human'),
        default=False,
    )
    
    indifferent = models.BooleanField(
        help_text=_('Is squirrel indifferent with human'),
        default=False,
    )
    
    runs_from = models.BooleanField(
        help_text=_('Is squirrel avoiding human'),
        default=False,
    )
    
    def __str__(self):
        return self.unique_squirrel_id
    
    

app/forms.py
from django.forms import ModelForm

from .models import Squirrel


class SquirrelForm(ModelForm):
    class Meta:
        model = Squirrel
        fields = '__all__'

app/views.py
from django.shortcuts import render
from django.shortcuts import get_object_or_404
from django.http import HttpResponse
from django.http import JsonResponse

from .models import Squirrel
from .forms import SquirrelForm

# Create your views here.

def mainpage(request):

    return render(request, 'app/mainpage.html', {})

def list(request):

    squirrels = Squirrel.objects.all()
    context = {
        'squirrels': squirrels,
    }

    return render(request, 'app/list.html', context)

def edit(request, unique_squirrel_id):
    
    squirrel = get_object_or_404(Squirrel, pk=unique_squirrel_id)
    
    if request.method == 'POST':
        form = SquirrelForm(request.POST)
        if form.is_valid():
            form.save()
            squirrels = Squirrel.objects.all()
            context = {
                'squirrels': squirrels,
            }
            return render(request, 'app/list.html', context)
    else:
        form = SquirrelForm(instance = squirrel)
        context = {
            'form': form,
        }
        return render(request, 'app/edit.html', context)

def add(request):

    if request.method == 'POST':
        form = SquirrelForm(request.POST)
        if form.is_valid():
            form.save()
            squirrels = Squirrel.objects.all()
            context = {
                'squirrels': squirrels,
            }
            return render(request, 'app/list.html', context)
        else:
            return JsonResponse({'errors': form.errors}, status=400)
    else:
        form = SquirrelForm()
        context = {
                'form': form,
            }
        return render(request, 'app/edit.html', context)

def map(request):
    part_squirrels = Squirrel.objects.all()[:100]

    context = {
            'part_squirrels': part_squirrels,
    }
    return render(request, 'app/map.html', context)

def stats(request):

    am_count = Squirrel.objects.filter(shift = 'AM').count()
    pm_count = Squirrel.objects.filter(shift = 'PM').count()
    ground_count = Squirrel.objects.filter(location = 'Ground Plane').count()
    running_count = Squirrel.objects.filter(running = True).count()
    adult_count = Squirrel.objects.filter(age = 'Adult').count()
    total_number = len(Squirrel.objects.all())
    
    context = {
        'total_number': total_number,
        'am_count': am_count,
        'pm_count': pm_count,
        'adult_count': adult_count,
        'ground_count': ground_count,
        'running_count': running_count,
    }

    return render(request, 'app/stats.html', context)

app/templates/app/edit.html
<!doctype html>

<html>
    <body>
        <form method = "POST">
            {% csrf_token %}
            {{ form.as_p}}
            <br>
            <input type='submit' name="Confirm and Submit">
        </form>
    </body>
</html>

app/templates/app/list.html
<!doctype html>
<html>
    <head>
        <title>Sighting</title>
        <p><a href = '/'> Main page </a></p>
        <h1 align="center"> This is the list for Squirrels in Central park, New York City </h1>
    </head>
    <body>
        <h2> Below is the link to view general statistics:</h2>
        <ul>
	    <li><p><a href = '/sightings/stats/'>General Statistics</a></p></li>
        </ul>
        <h2> Below is the link to add a new squirrel:</h2>
        <ul>
            <li><p><a href = '/sightings/add/'> Add NEW squirrel </a></p></li>
        </ul>
        <h2> Click on the squirrel ID to view and update its relative data:</h2>
        <p>
            <ul>
                {% for s in squirrels %}
		<li><a href = "{% url 'app:edit' s.unique_squirrel_id %}">{{ s }}</a></li>
		   <ul>
		      <li>{{ s.date }}</li>
		   </ul>
                {% endfor %}
            </ul>
        </p >
    </body>
</html>

app/templates/app/mainpage.html
<!doctype html>

<html>
    <head>
        <title> Home Page </title>
        <h1 align="center"> Home for squirrels in central park! </h1>
    </head>
    <body>
        <p align="center"> Click on the links below to view the list or map </p >
        <ul>
            <li><p><a href = '/sightings'> List of squrirrels </ a></p ></li>
            <li><p><a href = '/map'> Visualizing squirrels on map </ a></p ></li>
    </body>
</html>

app/templates/app/map.html
<!DOCTYPE html>
<html lang="en">
  <head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">

    <link rel="stylesheet"
          href="https://unpkg.com/leaflet@1.5.1/dist/leaflet.css"
          integrity="sha512-xwE/Az9zrjBIphAcBb3F6JVqxf46+CDLwfLMHloNu6KEQCAWi6HcDUbeOfBIptF7tcCzusKFjFw2yuvEpDL9wQ=="
          crossorigin=""/>
    <!-- Make sure you put this AFTER Leaflet's CSS -->
    <script src="https://unpkg.com/leaflet@1.5.1/dist/leaflet.js"
            integrity="sha512-GffPMF3RvMeYyc1LWMHtK8EbPv0iNZ8/oTtHPx9/cc2ILxQ+u905qIwdpULaqDkyBKgOaB57QTMg7ztg8Jm2Og=="
            crossorigin=""></script>

    <style>
      html,body {
        height: 100%;
      }
    </style>
  </head>
  <body>
    <div id="map" class="container-fluid h-100"></div>

    <!-- Optional JavaScript -->
    <!-- jQuery first, then Popper.js, then Bootstrap JS -->
    <script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js" integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q" crossorigin="anonymous"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js" integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl" crossorigin="anonymous"></script>

    <!-- Leaflet JS -->
    <script>
        var map_center = [
            40.782091,  // Latitude
            -73.964285  // Longitude
        ];
        var zoom_level = 14;
        var map = L.map('map').setView(map_center, zoom_level);
        L.tileLayer('https://{server}.tile.openstreetmap.org/{z}/{x}/{y}.png', {
            server: 'a',  // can be 'a', 'b', or 'c'
            // must leave attribution in!
            attribution: '&copy; <a href="https://www.openstreetmap.org/copyright">OpenStreetMap</a> contributors',
        }).addTo(map);

        <!-- L.Icon.Default.prototype.options.iconSize = 15; -->
        <!-- L.Icon.Default.prototype.options.iconAnchor = [0, 0]; -->
        <!-- L.Icon.Default.prototype.options.shadowSize = 15; -->
        <!-- L.Icon.Default.prototype.options.shadowAnchor = [0, 0]; -->

        {% for sighting in part_squirrels %}
          var point_lat_lon = [{{ sighting.Y }}, {{ sighting.X }}];
          var marker = L.marker(point_lat_lon).addTo(map);
        {% endfor %}
    </script>
  </body>
</html>

app/templates/app/stats.html
<!doctype html>

<html>
    <head>
        <title> Stats Page </title>
        <a href='/sightings'> Back to list of squirrels</a>
        <h1 align="center"> General Statistics for Squirrels in Central Park, NYC </h1>
    </head>
    <body>
        <p><ul>
        <li> Total number of squirrels: {{ total_number }}</li><br>
        <li> Count of Shift:
            <ul>
                <li>AM: {{ am_count }}</li>
                <li>PM: {{ pm_count }}</li>
            </ul>
        <li>Number of adult squirrels: {{ adult_count }}</li><br>
        <li>Number of squirrels on the ground: {{ ground_count }}</li><br>
        <li>Number of running squirrels: {{ running_count }}</li><br>
        </ul></p>
    </body>
</html>